version: '3'
services:
  auth_server:
    build: ./auth_server
    ports:
      - "5001:5001"
    networks:
      service_network:
        ipv4_address: 172.20.0.3

  resource_api:
    build: ./resource_api
    ports:
      - "5000:5000"
    depends_on:
      - auth_server
    networks:
      service_network:
        ipv4_address: 172.20.0.2
    environment:
      - AUTH_SERVER_URL_DOCKER=http://auth_server:5001

networks:
  service_network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
    driver: bridge

